using Portal.Portal.Persistence.Migrations;
using System.Threading;

namespace Portal.Portal.Web.Api.Pages.Shared.Resource.Models
{
    public class EmploymentModuleResourceModel
    {
        public string DeleteFormerPositionText { get; set; }
        public string AccountNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string IdExpirationDate { get; set; }
        public string EmployeesSalary { get; set; }
        public string NextStep { get; set; }
        public string WorkAddress { get; set; }
        public string Education { get; set; }
        public string SearchInAllColumns { get; set; }
        public string DeleteFormerPosition { get; set; }
        public string Gender { get; set; }
        public string Previous { get; set; }
        public string MaritalStatus { get; set; }
        public string SkillsAndLanguages { get; set; }
        public string EmployeeId { get; set; }
        public string Cancel { get; set; }
        public string WorkHours { get; set; }
        public string Create { get; set; }
        public string DeleteUniversity { get; set; }
        public string BankCode { get; set; }
        public string EditFormerPosition { get; set; }
        public string DeleteText { get; set; }
        public string Update { get; set; }
        public string EmployeeRole { get; set; }
        public string TimeZone { get; set; }
        public string EditUniversity { get; set; }
        public string Residency { get; set; }
        public string OtherInformation { get; set; }
        public string DeleteUniversityText { get; set; }
        public string Languages { get; set; }
        public string Schedule { get; set; }
        public string FormerPosition { get; set; }
        public string Resume { get; set; }
        public string Region { get; set; }
        public string Status { get; set; }
        public string String { get; set; }
        public string Skills { get; set; }
        public string DeleteTraining { get; set; }
        public string Position { get; set; }
        public string ExportToPdf { get; set; }
        public string JobInfo { get; set; }
        public string JobType { get; set; }
        public string GrossSalary { get; set; }
        public string DeleteTrainingText { get; set; }
        public string AddFormerPosition { get; set; }
        public string DateOfBirth { get; set; }
        public string PersonalInformation { get; set; }
        public string Language { get; set; }
        public string DeleteProfilePicture { get; set; }
        public string Alergies { get; set; }
        public string LegalAddress { get; set; }
        public string TheRoleOfTheEmployee { get; set; }
        public string FullName { get; set; }
        public string Training { get; set; }
        public string AddTraining { get; set; }
        public string AddEmployee { get; set; }
        public string AddUniversity { get; set; }
        public string JobStartDate { get; set; }
        public string DatesAttended { get; set; }
        public string ComputerSkills { get; set; }
        public string EmergencyContact { get; set; }
        public string End { get; set; }
        public string NetSalary { get; set; }
        public string Email { get; set; }
        public string Files { get; set; }
        public string PersonalId { get; set; }
        public string ActualAddress { get; set; }
        public string ParticipationInPension { get; set; }
        public string Start { get; set; }
        public string OtherInfo { get; set; }
        public string EmploymentHistory { get; set; }
        public string Contract { get; set; }
        public string PayrollBasic { get; set; }
        public string MedicalCertificate { get; set; }
        public string ContractExpirationDate { get; set; }
        public string EmployeeList { get; set; }
        public string JobInformation { get; set; }
        public string EditTraining { get; set; }
        public string DeleteProfilePictureText { get; set; }
        public string CompanyPension { get; set; }
        public string Conviction { get; set; }
        public string University { get; set; }
        public string FormerPositions { get; set; }
        public string BloodGroupAndRhesus { get; set; }
        public string DrivingLicense { get; set; }
        public string Department { get; set; }
        public string IncomeTax { get; set; }
        public string Faculty { get; set; }
        public string EmployeeProfile { get; set; }
        public string Relationship { get; set; }
        public string ExportToExcel { get; set; }
        public string ItemsPerPage { get; set; }
        public string EmployeePension { get; set; }
        public string ComputerSkill { get; set; }
        public string EmployementHistory { get; set; }
        public string Bank { get; set; }
        public string View { get; set; }
        public string Role { get; set; }
        public string Save { get; set; }
        public string Upload { get; set; }
        public string BOG { get; set; }
        public string TBC { get; set; }
        public string BASIS { get; set; }
        public string CARTU { get; set; }
        public string Convicted { get; set; }
        public string NonConvicted { get; set; }
        public string Active { get; set; }
        public string Passive { get; set; }
        public string Male { get; set; }
        public string Female { get; set; }
        public string Married { get; set; }
        public string Single { get; set; }
        public string Resident { get; set; }
        public string NonResident { get; set; }
        public string Yes { get; set; }
        public string No { get; set; }
        public string FullTime { get; set; }
        public string PartTime { get; set; }
        public string IdDocument { get; set; }
        public string Supervisor { get; set; }
        public string ContractTypes { get; set; }
        public string ContractType { get; set; }
        public string EmployeesExcelImportFile { get; set; }
    }
}
