export * from './employee.service';
import { EmployeeService } from './employee.service';
export * from './employeeProfile.service';
import { EmployeeProfileService } from './employeeProfile.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './logIn.service';
import { LogInService } from './logIn.service';
export * from './nonCompliance.service';
import { NonComplianceService } from './nonCompliance.service';
export * from './parametres.service';
import { ParametresService } from './parametres.service';
export * from './resource.service';
import { ResourceService } from './resource.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './timeOffRequest.service';
import { TimeOffRequestService } from './timeOffRequest.service';
export const APIS = [EmployeeService, EmployeeProfileService, FilesService, LogInService, NonComplianceService, ParametresService, ResourceService, RolesService, TimeOffRequestService];
