/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AllTimeOffRequestsResponseResult } from '../model/allTimeOffRequestsResponseResult';
import { EmployeesResponseResult } from '../model/employeesResponseResult';
import { GetRecipientsResponseResult } from '../model/getRecipientsResponseResult';
import { IEntityArrayResult } from '../model/iEntityArrayResult';
import { ReceivedTimeOffRequestHistoryResponseResult } from '../model/receivedTimeOffRequestHistoryResponseResult';
import { ReceivedTimeOffRequestsResponseResult } from '../model/receivedTimeOffRequestsResponseResult';
import { Recipient } from '../model/recipient';
import { SentTimeOffRequestDetailsResponseResult } from '../model/sentTimeOffRequestDetailsResponseResult';
import { SentTimeOffRequestsResponseResult } from '../model/sentTimeOffRequestsResponseResult';
import { TimeOffRequestHistoryResponseResult } from '../model/timeOffRequestHistoryResponseResult';
import { TimeOffRequestStatus } from '../model/timeOffRequestStatus';
import { TimeOffRequestType } from '../model/timeOffRequestType';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class TimeOffRequestService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param search 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestAlltimeoffrequestsGet(search?: string, observe?: 'body', reportProgress?: boolean): Observable<AllTimeOffRequestsResponseResult>;
    public apiTimeoffrequestAlltimeoffrequestsGet(search?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AllTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestAlltimeoffrequestsGet(search?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AllTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestAlltimeoffrequestsGet(search?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('Search', <any>search);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AllTimeOffRequestsResponseResult>('get',`${this.basePath}/api/timeoffrequest/alltimeoffrequests`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param status 
     * @param comment 
     * @param file 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestChangereceivedtimeoffrequeststatusPostForm(number?: string, status?: TimeOffRequestStatus, comment?: string, file?: Blob, observe?: 'body', reportProgress?: boolean): Observable<IEntityArrayResult>;
    public apiTimeoffrequestChangereceivedtimeoffrequeststatusPostForm(number?: string, status?: TimeOffRequestStatus, comment?: string, file?: Blob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IEntityArrayResult>>;
    public apiTimeoffrequestChangereceivedtimeoffrequeststatusPostForm(number?: string, status?: TimeOffRequestStatus, comment?: string, file?: Blob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IEntityArrayResult>>;
    public apiTimeoffrequestChangereceivedtimeoffrequeststatusPostForm(number?: string, status?: TimeOffRequestStatus, comment?: string, file?: Blob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (number !== undefined) {
            formParams = formParams.append('Number', <any>number) as any || formParams;
        }
        if (status !== undefined) {
            formParams = formParams.append('Status', <any>status) as any || formParams;
        }
        if (comment !== undefined) {
            formParams = formParams.append('Comment', <any>comment) as any || formParams;
        }
        if (file !== undefined) {
            formParams = formParams.append('File', <any>file) as any || formParams;
        }

        return this.httpClient.request<IEntityArrayResult>('post',`${this.basePath}/api/timeoffrequest/changereceivedtimeoffrequeststatus`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param type 
     * @param title 
     * @param recipient 
     * @param receiver 
     * @param deadLine 
     * @param from 
     * @param including 
     * @param file 
     * @param description 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestCreatetimeoffrequestPostForm(type?: TimeOffRequestType, title?: string, recipient?: Recipient, receiver?: string, deadLine?: string, from?: string, including?: string, file?: Blob, description?: string, observe?: 'body', reportProgress?: boolean): Observable<IEntityArrayResult>;
    public apiTimeoffrequestCreatetimeoffrequestPostForm(type?: TimeOffRequestType, title?: string, recipient?: Recipient, receiver?: string, deadLine?: string, from?: string, including?: string, file?: Blob, description?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IEntityArrayResult>>;
    public apiTimeoffrequestCreatetimeoffrequestPostForm(type?: TimeOffRequestType, title?: string, recipient?: Recipient, receiver?: string, deadLine?: string, from?: string, including?: string, file?: Blob, description?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IEntityArrayResult>>;
    public apiTimeoffrequestCreatetimeoffrequestPostForm(type?: TimeOffRequestType, title?: string, recipient?: Recipient, receiver?: string, deadLine?: string, from?: string, including?: string, file?: Blob, description?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {










        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (type !== undefined) {
            formParams = formParams.append('Type', <any>type) as any || formParams;
        }
        if (title !== undefined) {
            formParams = formParams.append('Title', <any>title) as any || formParams;
        }
        if (recipient !== undefined) {
            formParams = formParams.append('Recipient', <any>recipient) as any || formParams;
        }
        if (receiver !== undefined) {
            formParams = formParams.append('Receiver', <any>receiver) as any || formParams;
        }
        if (deadLine !== undefined) {
            formParams = formParams.append('DeadLine', <any>deadLine) as any || formParams;
        }
        if (from !== undefined) {
            formParams = formParams.append('From', <any>from) as any || formParams;
        }
        if (including !== undefined) {
            formParams = formParams.append('Including', <any>including) as any || formParams;
        }
        if (file !== undefined) {
            formParams = formParams.append('File', <any>file) as any || formParams;
        }
        if (description !== undefined) {
            formParams = formParams.append('Description', <any>description) as any || formParams;
        }

        return this.httpClient.request<IEntityArrayResult>('post',`${this.basePath}/api/timeoffrequest/createtimeoffrequest`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestDeletetimeoffrequestPostForm(number?: string, observe?: 'body', reportProgress?: boolean): Observable<IEntityArrayResult>;
    public apiTimeoffrequestDeletetimeoffrequestPostForm(number?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IEntityArrayResult>>;
    public apiTimeoffrequestDeletetimeoffrequestPostForm(number?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IEntityArrayResult>>;
    public apiTimeoffrequestDeletetimeoffrequestPostForm(number?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (number !== undefined) {
            formParams = formParams.append('Number', <any>number) as any || formParams;
        }

        return this.httpClient.request<IEntityArrayResult>('post',`${this.basePath}/api/timeoffrequest/deletetimeoffrequest`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param search 
     * @param nonComplianceId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestEmployeesGet(search?: string, nonComplianceId?: string, observe?: 'body', reportProgress?: boolean): Observable<EmployeesResponseResult>;
    public apiTimeoffrequestEmployeesGet(search?: string, nonComplianceId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EmployeesResponseResult>>;
    public apiTimeoffrequestEmployeesGet(search?: string, nonComplianceId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EmployeesResponseResult>>;
    public apiTimeoffrequestEmployeesGet(search?: string, nonComplianceId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('Search', <any>search);
        }
        if (nonComplianceId !== undefined && nonComplianceId !== null) {
            queryParameters = queryParameters.set('NonComplianceId', <any>nonComplianceId);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EmployeesResponseResult>('get',`${this.basePath}/api/timeoffrequest/employees`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestGetrecipientsGet(observe?: 'body', reportProgress?: boolean): Observable<GetRecipientsResponseResult>;
    public apiTimeoffrequestGetrecipientsGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GetRecipientsResponseResult>>;
    public apiTimeoffrequestGetrecipientsGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GetRecipientsResponseResult>>;
    public apiTimeoffrequestGetrecipientsGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GetRecipientsResponseResult>('get',`${this.basePath}/api/timeoffrequest/getrecipients`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestReceivedtimeoffrequesthistoryGet(number: string, observe?: 'body', reportProgress?: boolean): Observable<ReceivedTimeOffRequestHistoryResponseResult>;
    public apiTimeoffrequestReceivedtimeoffrequesthistoryGet(number: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReceivedTimeOffRequestHistoryResponseResult>>;
    public apiTimeoffrequestReceivedtimeoffrequesthistoryGet(number: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReceivedTimeOffRequestHistoryResponseResult>>;
    public apiTimeoffrequestReceivedtimeoffrequesthistoryGet(number: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (number === null || number === undefined) {
            throw new Error('Required parameter number was null or undefined when calling apiTimeoffrequestReceivedtimeoffrequesthistoryGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (number !== undefined && number !== null) {
            queryParameters = queryParameters.set('Number', <any>number);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReceivedTimeOffRequestHistoryResponseResult>('get',`${this.basePath}/api/timeoffrequest/receivedtimeoffrequesthistory`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param search 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestReceivedtimeoffrequestsGet(search?: string, observe?: 'body', reportProgress?: boolean): Observable<ReceivedTimeOffRequestsResponseResult>;
    public apiTimeoffrequestReceivedtimeoffrequestsGet(search?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReceivedTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestReceivedtimeoffrequestsGet(search?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReceivedTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestReceivedtimeoffrequestsGet(search?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('Search', <any>search);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReceivedTimeOffRequestsResponseResult>('get',`${this.basePath}/api/timeoffrequest/receivedtimeoffrequests`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param participant 
     * @param file 
     * @param comment 
     * @param rightOfConfirmation 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestRedirecttimeoffrequestPostForm(number?: string, participant?: string, file?: Blob, comment?: string, rightOfConfirmation?: boolean, observe?: 'body', reportProgress?: boolean): Observable<IEntityArrayResult>;
    public apiTimeoffrequestRedirecttimeoffrequestPostForm(number?: string, participant?: string, file?: Blob, comment?: string, rightOfConfirmation?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IEntityArrayResult>>;
    public apiTimeoffrequestRedirecttimeoffrequestPostForm(number?: string, participant?: string, file?: Blob, comment?: string, rightOfConfirmation?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IEntityArrayResult>>;
    public apiTimeoffrequestRedirecttimeoffrequestPostForm(number?: string, participant?: string, file?: Blob, comment?: string, rightOfConfirmation?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (number !== undefined) {
            formParams = formParams.append('Number', <any>number) as any || formParams;
        }
        if (participant !== undefined) {
            formParams = formParams.append('Participant', <any>participant) as any || formParams;
        }
        if (file !== undefined) {
            formParams = formParams.append('File', <any>file) as any || formParams;
        }
        if (comment !== undefined) {
            formParams = formParams.append('Comment', <any>comment) as any || formParams;
        }
        if (rightOfConfirmation !== undefined) {
            formParams = formParams.append('RightOfConfirmation', <any>rightOfConfirmation) as any || formParams;
        }

        return this.httpClient.request<IEntityArrayResult>('post',`${this.basePath}/api/timeoffrequest/redirecttimeoffrequest`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestSenttimeoffrequestdetailsGet(number: string, observe?: 'body', reportProgress?: boolean): Observable<SentTimeOffRequestDetailsResponseResult>;
    public apiTimeoffrequestSenttimeoffrequestdetailsGet(number: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SentTimeOffRequestDetailsResponseResult>>;
    public apiTimeoffrequestSenttimeoffrequestdetailsGet(number: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SentTimeOffRequestDetailsResponseResult>>;
    public apiTimeoffrequestSenttimeoffrequestdetailsGet(number: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (number === null || number === undefined) {
            throw new Error('Required parameter number was null or undefined when calling apiTimeoffrequestSenttimeoffrequestdetailsGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (number !== undefined && number !== null) {
            queryParameters = queryParameters.set('Number', <any>number);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SentTimeOffRequestDetailsResponseResult>('get',`${this.basePath}/api/timeoffrequest/senttimeoffrequestdetails`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param search 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestSenttimeoffrequestsGet(search?: string, observe?: 'body', reportProgress?: boolean): Observable<SentTimeOffRequestsResponseResult>;
    public apiTimeoffrequestSenttimeoffrequestsGet(search?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SentTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestSenttimeoffrequestsGet(search?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SentTimeOffRequestsResponseResult>>;
    public apiTimeoffrequestSenttimeoffrequestsGet(search?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (search !== undefined && search !== null) {
            queryParameters = queryParameters.set('Search', <any>search);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SentTimeOffRequestsResponseResult>('get',`${this.basePath}/api/timeoffrequest/senttimeoffrequests`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param number 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiTimeoffrequestTimeoffrequesthistoryGet(number: string, observe?: 'body', reportProgress?: boolean): Observable<TimeOffRequestHistoryResponseResult>;
    public apiTimeoffrequestTimeoffrequesthistoryGet(number: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TimeOffRequestHistoryResponseResult>>;
    public apiTimeoffrequestTimeoffrequesthistoryGet(number: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TimeOffRequestHistoryResponseResult>>;
    public apiTimeoffrequestTimeoffrequesthistoryGet(number: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (number === null || number === undefined) {
            throw new Error('Required parameter number was null or undefined when calling apiTimeoffrequestTimeoffrequesthistoryGet.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (number !== undefined && number !== null) {
            queryParameters = queryParameters.set('Number', <any>number);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<TimeOffRequestHistoryResponseResult>('get',`${this.basePath}/api/timeoffrequest/timeoffrequesthistory`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
