/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ActionPermissions { 
    addEmployee?: boolean;
    viewEmployeesList?: boolean;
    viewEmployeeProfile?: boolean;
    editPersonalInformation?: boolean;
    editJobInfo?: boolean;
    editEducation?: boolean;
    editPayrollBasic?: boolean;
    editEmploymentHistory?: boolean;
    editSkillsAndLanguages?: boolean;
    editOtherInfo?: boolean;
    allTimeOffRequests?: boolean;
    allNonCompliances?: boolean;
    viewAdminPanel?: boolean;
    viewRoles?: boolean;
}