/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface AuthorizationModuleResourceModel { 
    login?: string;
    emailAddress?: string;
    password?: string;
    forgotPassword?: string;
    welcomeBack?: string;
    pleaseEnterDetails?: string;
    rememberThisDevise?: string;
    noWorries?: string;
    resetPassword?: string;
    returnTo?: string;
    checkYourEmail?: string;
    weSentPasswordLinkTo?: string;
    openEmail?: string;
    didntReceiveTheEmail?: string;
    clickToSend?: string;
    setNewPassword?: string;
    yourNewPasswordMustBeDifferent?: string;
    repeatPassword?: string;
    passwordHasBeenReset?: string;
    yourPasswordHasBeenSuccessfullyReset?: string;
    clickBelowToLogIn?: string;
}