/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type Bank = 'BOG' | 'TBC' | 'BASIS' | 'CARTU';

export const Bank = {
    BOG: 'BOG' as Bank,
    TBC: 'TBC' as Bank,
    BASIS: 'BASIS' as Bank,
    CARTU: 'CARTU' as Bank
};