/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ContractTypesListResponse } from './contractTypesListResponse';
import { ContractTypesListResponseErrorModel } from './contractTypesListResponseErrorModel';

export interface ContractTypesListResponseResult { 
    ok?: boolean;
    errors?: ContractTypesListResponseErrorModel;
    value?: ContractTypesListResponse;
}