/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Bank } from './bank';
import { ParticipationInPension } from './participationInPension';
import { Residency } from './residency';

export interface EditEmployeePayrollBasicRequest { 
    id?: number;
    bank?: Bank;
    bankCode?: string;
    accountNumber?: string;
    residency?: Residency;
    participationInPension?: ParticipationInPension;
    grossSalary?: number;
    netSalary?: number;
    incomeTax?: number;
    companyPension?: number;
    employeePension?: number;
}