/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmployeeStatus } from './employeeStatus';
import { JobType } from './jobType';

export interface EditEmployeePersonalInformationRequest { 
    id?: number;
    fullName?: string;
    position?: string;
    phoneNumber?: string;
    email?: string;
    dateOfBirth?: Date;
    personalId?: string;
    status?: EmployeeStatus;
    jobType?: JobType;
}