/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface EmploymentModuleResourceModel { 
    deleteFormerPositionText?: string;
    accountNumber?: string;
    phoneNumber?: string;
    idExpirationDate?: string;
    employeesSalary?: string;
    nextStep?: string;
    workAddress?: string;
    education?: string;
    searchInAllColumns?: string;
    deleteFormerPosition?: string;
    gender?: string;
    previous?: string;
    maritalStatus?: string;
    skillsAndLanguages?: string;
    employeeId?: string;
    cancel?: string;
    workHours?: string;
    create?: string;
    deleteUniversity?: string;
    bankCode?: string;
    editFormerPosition?: string;
    deleteText?: string;
    update?: string;
    employeeRole?: string;
    timeZone?: string;
    editUniversity?: string;
    residency?: string;
    otherInformation?: string;
    deleteUniversityText?: string;
    languages?: string;
    schedule?: string;
    formerPosition?: string;
    resume?: string;
    region?: string;
    status?: string;
    string?: string;
    skills?: string;
    deleteTraining?: string;
    position?: string;
    exportToPdf?: string;
    jobInfo?: string;
    jobType?: string;
    grossSalary?: string;
    deleteTrainingText?: string;
    addFormerPosition?: string;
    dateOfBirth?: string;
    personalInformation?: string;
    language?: string;
    deleteProfilePicture?: string;
    alergies?: string;
    legalAddress?: string;
    theRoleOfTheEmployee?: string;
    fullName?: string;
    training?: string;
    addTraining?: string;
    addEmployee?: string;
    addUniversity?: string;
    jobStartDate?: string;
    datesAttended?: string;
    computerSkills?: string;
    emergencyContact?: string;
    end?: string;
    netSalary?: string;
    email?: string;
    files?: string;
    personalId?: string;
    actualAddress?: string;
    participationInPension?: string;
    start?: string;
    otherInfo?: string;
    employmentHistory?: string;
    contract?: string;
    payrollBasic?: string;
    medicalCertificate?: string;
    contractExpirationDate?: string;
    employeeList?: string;
    jobInformation?: string;
    editTraining?: string;
    deleteProfilePictureText?: string;
    companyPension?: string;
    conviction?: string;
    university?: string;
    formerPositions?: string;
    bloodGroupAndRhesus?: string;
    drivingLicense?: string;
    department?: string;
    incomeTax?: string;
    faculty?: string;
    employeeProfile?: string;
    relationship?: string;
    exportToExcel?: string;
    itemsPerPage?: string;
    employeePension?: string;
    computerSkill?: string;
    employementHistory?: string;
    bank?: string;
    view?: string;
    role?: string;
    save?: string;
    upload?: string;
    bog?: string;
    tbc?: string;
    basis?: string;
    cartu?: string;
    convicted?: string;
    nonConvicted?: string;
    active?: string;
    passive?: string;
    male?: string;
    female?: string;
    married?: string;
    single?: string;
    resident?: string;
    nonResident?: string;
    yes?: string;
    no?: string;
    fullTime?: string;
    partTime?: string;
    idDocument?: string;
    supervisor?: string;
    contractTypes?: string;
    contractType?: string;
    employeesExcelImportFile?: string;
}