/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EmployeeFileModel } from './employeeFileModel';
import { TimeZoneModel } from './timeZoneModel';

export interface EmployeeJobInfoResponse { 
    id?: number;
    region?: string;
    workAddress?: string;
    idDocument?: EmployeeFileModel;
    idExpirationDate?: Date;
    department?: string;
    timeZone?: TimeZoneModel;
}