/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ErrorResourceModel { 
    phoneNumber?: string;
    position?: string;
    jobType?: string;
    dateOfBirth?: string;
    fullName?: string;
    emailValid?: string;
    emailEmpty?: string;
    personalId?: string;
    university?: string;
    faculty?: string;
    startYear?: string;
    endYear?: string;
    formerPosition?: string;
    training?: string;
    skill?: string;
    language?: string;
    title?: string;
    receiver?: string;
    endDateGreaterThanStartDate?: string;
    status?: string;
    participant?: string;
    contractTermGreaterThanJobStartDate?: string;
    from?: string;
    to?: string;
    violator?: string;
    description?: string;
    group?: string;
    including?: string;
    pleaseFillTheFollowingFields?: string;
    contractType?: string;
    comment?: string;
    hrWhoReceivesTimeOffRequests?: string;
    recipient?: string;
    password?: string;
    repeatPassword?: string;
    passwordDoesNotMatch?: string;
    roleName?: string;
}