/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FileType = 'Word' | 'Excel' | 'PowerPoint' | 'PDF' | 'Image' | 'File';

export const FileType = {
    Word: 'Word' as FileType,
    Excel: 'Excel' as FileType,
    PowerPoint: 'PowerPoint' as FileType,
    PDF: 'PDF' as FileType,
    Image: 'Image' as FileType,
    File: 'File' as FileType
};