/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type JobType = 'FullTime' | 'PartTime';

export const JobType = {
    FullTime: 'FullTime' as JobType,
    PartTime: 'PartTime' as JobType
};