/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LayoutResourcesModel { 
    dashboard?: string;
    employeeList?: string;
    schedule?: string;
    log?: string;
    timeOffRequests?: string;
    nonCompliance?: string;
    payroll?: string;
    checklists?: string;
    tasks?: string;
    devices?: string;
    contacts?: string;
    logOut?: string;
    viewMyProfile?: string;
    accountSettings?: string;
    support?: string;
    roles?: string;
    parametres?: string;
}