/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NonComplianceFileModel } from './nonComplianceFileModel';
import { NonComplianceRedirectModel } from './nonComplianceRedirectModel';
import { NonComplianceStatus } from './nonComplianceStatus';

export interface MyNonComplianceDetailsResponse { 
    number?: string;
    group?: string;
    sender?: string;
    approvalDeadline?: Date;
    date?: Date;
    fine?: number;
    file?: NonComplianceFileModel;
    description?: string;
    myComment?: string;
    myFile?: NonComplianceFileModel;
    status?: NonComplianceStatus;
    statusChanger?: string;
    statusComment?: string;
    statusChangeDate?: Date;
    statusFile?: NonComplianceFileModel;
    redirects?: Array<NonComplianceRedirectModel>;
}