/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type NonComplianceStatus = 'InProgress' | 'Excusable' | 'Inexcusable';

export const NonComplianceStatus = {
    InProgress: 'InProgress' as NonComplianceStatus,
    Excusable: 'Excusable' as NonComplianceStatus,
    Inexcusable: 'Inexcusable' as NonComplianceStatus
};