/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface NonComplianceResourcesModel { 
    group?: string;
    title?: string;
    violator?: string;
    sender?: string;
    fine?: string;
    description?: string;
    file?: string;
    content?: string;
    date?: string;
    status?: string;
    details?: string;
    groups?: string;
    createNew?: string;
    insertGroup?: string;
    save?: string;
    cancel?: string;
    create?: string;
    all?: string;
    sent?: string;
    received?: string;
    nonCompliance?: string;
    deleteNonCompliance?: string;
    _delete?: string;
    myViolations?: string;
    violations?: string;
    allNonComplianceDetails?: string;
    redirect?: string;
    attachedFile?: string;
    comment?: string;
    violatorResponse?: string;
    statusChange?: string;
    receiver?: string;
    redirecting?: string;
    history?: string;
    changeStatus?: string;
    statusComment?: string;
    statusFile?: string;
    sentNonComplianceDetails?: string;
    receivedNonComplianceDetails?: string;
    myNonComplianceDetails?: string;
    addComment?: string;
    add?: string;
    myComment?: string;
    onGoing?: string;
    inProgress?: string;
    excusable?: string;
    inexcusable?: string;
    dateCreated?: string;
    upload?: string;
    statusChangeDate?: string;
    approvalDeadLine?: string;
    ifAplicable?: string;
    search?: string;
}