/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ParametresResourceModel { 
    adminPanel?: string;
    employeeService?: string;
    nonCompliance?: string;
    contractType?: string;
    employeesExcelImportFile?: string;
    download?: string;
    save?: string;
    cancel?: string;
    groups?: string;
    group?: string;
    timeOffRequest?: string;
    hrWhoReceivesTimeOffRequests?: string;
    hr?: string;
    parametres?: string;
}