/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdminPanelPermissionsModel } from './adminPanelPermissionsModel';
import { EmployeePermissionsModel } from './employeePermissionsModel';
import { NonCompliancePermissionsModel } from './nonCompliancePermissionsModel';
import { RolesPermissionsModel } from './rolesPermissionsModel';
import { TimeOffRequestPermissionsModel } from './timeOffRequestPermissionsModel';

export interface PermissionsResponse { 
    employeeModule?: EmployeePermissionsModel;
    timeOffRequestModule?: TimeOffRequestPermissionsModel;
    nonComlianceModule?: NonCompliancePermissionsModel;
    adminPanelModule?: AdminPanelPermissionsModel;
    rolesModel?: RolesPermissionsModel;
}