/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RedirectModel } from './redirectModel';
import { TimeOffRequestFileModel } from './timeOffRequestFileModel';
import { TimeOffRequestStatus } from './timeOffRequestStatus';
import { TimeOffRequestType } from './timeOffRequestType';

export interface ReceivedTimeOffRequestHistoryResponse { 
    type?: TimeOffRequestType;
    number?: string;
    title?: string;
    sender?: string;
    date?: Date;
    deadLine?: Date;
    from?: Date;
    including?: Date;
    file?: TimeOffRequestFileModel;
    description?: string;
    status?: TimeOffRequestStatus;
    statusChanger?: string;
    statusComment?: string;
    statusChangeDate?: Date;
    statusFile?: TimeOffRequestFileModel;
    redirects?: Array<RedirectModel>;
    isStatusChanger?: boolean;
}