/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupModel } from './groupModel';
import { RoleUserModel } from './roleUserModel';

export interface RoleDetailsResponse { 
    id?: number;
    name?: string;
    description?: string;
    groups?: Array<GroupModel>;
    users?: Array<RoleUserModel>;
}