/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RolesModuleResourcesModel { 
    roles?: string;
    createNewRole?: string;
    view?: string;
    employees?: string;
    permissions?: string;
    name?: string;
    description?: string;
    numberOfEmployees?: string;
    details?: string;
    saveChanges?: string;
    addEmployee?: string;
    editRole?: string;
    employee?: string;
    enterEmployeeEmailAddress?: string;
    add?: string;
    cancel?: string;
    roleBasedOn?: string;
    createRole?: string;
    rolesList?: string;
    newRole?: string;
    employeeModule?: string;
    timeOffReqeustModule?: string;
    nonComlianceModule?: string;
    update?: string;
    fullName?: string;
    position?: string;
    deleteText?: string;
    adminPanelModule?: string;
    rolesModule?: string;
    deleteEmployeeFromTheRole?: string;
    thisActionWillDelete?: string;
    fromTheRoleList?: string;
}