/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TimeZoneEnum = 'Eniwetok_Kwajalein' | 'Midway_Island_Samoa' | 'Hawaii' | 'Taiohae' | 'Alaska' | 'Pacific_Time_US_Canada' | 'Mountain_Time_US_Canada' | 'Central_Time_US_Canada_Mexico_City' | 'Eastern_Time_US_Canada_Bogota_Lima' | 'Caracas' | 'Atlantic_Time_Canada_Caracas_La_Paz' | 'Newfoundland' | 'Brazil_Buenos_Aires_Georgetown' | 'Mid_Atlantic' | 'Azores_Cape_Verde_Islands' | 'Western_Europe_Time_London_Lisbon_Casablanca' | 'Brussels_Copenhagen_Madrid_Paris' | 'Kaliningrad_South_Africa' | 'Baghdad_Riyadh_Moscow_St_Petersburg' | 'Tehran' | 'Abu_Dhabi_Muscat_Baku_Tbilisi' | 'Kabul' | 'Ekaterinburg_Islamabad_Karachi_Tashkent' | 'Bombay_Calcutta_Madras_New_Delhi' | 'Kathmandu_Pokhara' | 'Almaty_Dhaka_Colombo' | 'Yangon_Mandalay' | 'Bangkok' | 'Beijing' | 'Eucla' | 'Tokyo' | 'Adelaide' | 'EasternAustralia' | 'LordHoweIsland' | 'Magadan' | 'NorfolkIsland' | 'Auckland' | 'ChathamIslands' | 'Apia' | 'LineIslands';

export const TimeZoneEnum = {
    EniwetokKwajalein: 'Eniwetok_Kwajalein' as TimeZoneEnum,
    MidwayIslandSamoa: 'Midway_Island_Samoa' as TimeZoneEnum,
    Hawaii: 'Hawaii' as TimeZoneEnum,
    Taiohae: 'Taiohae' as TimeZoneEnum,
    Alaska: 'Alaska' as TimeZoneEnum,
    PacificTimeUSCanada: 'Pacific_Time_US_Canada' as TimeZoneEnum,
    MountainTimeUSCanada: 'Mountain_Time_US_Canada' as TimeZoneEnum,
    CentralTimeUSCanadaMexicoCity: 'Central_Time_US_Canada_Mexico_City' as TimeZoneEnum,
    EasternTimeUSCanadaBogotaLima: 'Eastern_Time_US_Canada_Bogota_Lima' as TimeZoneEnum,
    Caracas: 'Caracas' as TimeZoneEnum,
    AtlanticTimeCanadaCaracasLaPaz: 'Atlantic_Time_Canada_Caracas_La_Paz' as TimeZoneEnum,
    Newfoundland: 'Newfoundland' as TimeZoneEnum,
    BrazilBuenosAiresGeorgetown: 'Brazil_Buenos_Aires_Georgetown' as TimeZoneEnum,
    MidAtlantic: 'Mid_Atlantic' as TimeZoneEnum,
    AzoresCapeVerdeIslands: 'Azores_Cape_Verde_Islands' as TimeZoneEnum,
    WesternEuropeTimeLondonLisbonCasablanca: 'Western_Europe_Time_London_Lisbon_Casablanca' as TimeZoneEnum,
    BrusselsCopenhagenMadridParis: 'Brussels_Copenhagen_Madrid_Paris' as TimeZoneEnum,
    KaliningradSouthAfrica: 'Kaliningrad_South_Africa' as TimeZoneEnum,
    BaghdadRiyadhMoscowStPetersburg: 'Baghdad_Riyadh_Moscow_St_Petersburg' as TimeZoneEnum,
    Tehran: 'Tehran' as TimeZoneEnum,
    AbuDhabiMuscatBakuTbilisi: 'Abu_Dhabi_Muscat_Baku_Tbilisi' as TimeZoneEnum,
    Kabul: 'Kabul' as TimeZoneEnum,
    EkaterinburgIslamabadKarachiTashkent: 'Ekaterinburg_Islamabad_Karachi_Tashkent' as TimeZoneEnum,
    BombayCalcuttaMadrasNewDelhi: 'Bombay_Calcutta_Madras_New_Delhi' as TimeZoneEnum,
    KathmanduPokhara: 'Kathmandu_Pokhara' as TimeZoneEnum,
    AlmatyDhakaColombo: 'Almaty_Dhaka_Colombo' as TimeZoneEnum,
    YangonMandalay: 'Yangon_Mandalay' as TimeZoneEnum,
    Bangkok: 'Bangkok' as TimeZoneEnum,
    Beijing: 'Beijing' as TimeZoneEnum,
    Eucla: 'Eucla' as TimeZoneEnum,
    Tokyo: 'Tokyo' as TimeZoneEnum,
    Adelaide: 'Adelaide' as TimeZoneEnum,
    EasternAustralia: 'EasternAustralia' as TimeZoneEnum,
    LordHoweIsland: 'LordHoweIsland' as TimeZoneEnum,
    Magadan: 'Magadan' as TimeZoneEnum,
    NorfolkIsland: 'NorfolkIsland' as TimeZoneEnum,
    Auckland: 'Auckland' as TimeZoneEnum,
    ChathamIslands: 'ChathamIslands' as TimeZoneEnum,
    Apia: 'Apia' as TimeZoneEnum,
    LineIslands: 'LineIslands' as TimeZoneEnum
};