/**
 * Demo API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TimeOffRequestResourcesModel { 
    requestTimeOff?: string;
    action?: string;
    timeOffRequests?: string;
    create?: string;
    number?: string;
    deadLIne?: string;
    status?: string;
    sender?: string;
    content?: string;
    details?: string;
    all?: string;
    title?: string;
    createTimeOffRequest?: string;
    received?: string;
    receiver?: string;
    description?: string;
    date?: string;
    sent?: string;
    search?: string;
    sentRequestDetails?: string;
    receivedRequestHistory?: string;
    redirect?: string;
    changeTimeOffRequestStatus?: string;
    comment?: string;
    save?: string;
    cancel?: string;
    redirecting?: string;
    participant?: string;
    rightOfConfirmation?: string;
    sentTo?: string;
    confirmedRequest?: string;
    rejectedRequest?: string;
    view?: string;
    contains?: string;
    file?: string;
    ongoing?: string;
    timeOffRequestHistory?: string;
    from?: string;
    including?: string;
    requestType?: string;
    vacation?: string;
    dayOff?: string;
    sickLeave?: string;
    custom?: string;
    inProgress?: string;
    confirmed?: string;
    rejected?: string;
    parentalLeave?: string;
    dateCreated?: string;
    confirm?: string;
    reject?: string;
    upload?: string;
    businessTrip?: string;
    unpaidVacation?: string;
    statusChangeDate?: string;
    recipient?: string;
    hr?: string;
    supervisor?: string;
    other?: string;
    remoteDay?: string;
}